ktor:
  application:
    modules:
      - QueuingManagementSystem.ApplicationKt.module
  deployment:
    port: 9000
postgres:
  url: "jdbc:postgresql://localhost:5432/queuing_db"
  user: "postgres"
  password: "root"
